# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9bfd41dcf431fddc155f7892b4bf21acfd2e96236c33ac911554b90f483e0ab837e289ee77924887bbd4bc7d7c2fe95025e72e11b279e8c303cef16888ade8ef
  stripe_pk: pk_test_AtYaBkebrWxHOLLClCUjAkzC
  stripe_sk: sk_test_LeuYroeD85Zuu1PhyJfCcSF3
test:
  secret_key_base: d6cee5e0de0843b2a8c52b1599c3d0a672ec726f006a03fb7bcdf052e2ce6c32db586b665c5b59031662e429ae34a3c82cfcff5484a41aded63441ead2731378

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_pk: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  stripe_Sk: <%= ENV["STRIPE_SECRET_KEY"] %>